// Code generated by github.com/induzo/enumgen DO NOT EDIT.
package book

import (
	"fmt"

	"github.com/goccy/go-json"
)

type Rating string

const (
	NotGood Rating = "not_good"
	Ok      Rating = "ok"
	Nice    Rating = "nice"
	Great   Rating = "great"
)

func (rat Rating) String() string {
	return string(rat)
}

type RatingParseError struct {
	Rating string `json:"data"`
}

func (e RatingParseError) Error() string {
	return "invalid Rating value: " + e.Rating
}

func ParseRatingFromString(rat string) (Rating, error) {
	switch rat {
	case NotGood.String():
		return NotGood, nil
	case Ok.String():
		return Ok, nil
	case Nice.String():
		return Nice, nil
	case Great.String():
		return Great, nil
	default:
		return "", RatingParseError{Rating: rat}
	}
}

func MustParseRatingFromString(rat string) Rating {
	g, err := ParseRatingFromString(rat)
	if err != nil {
		panic(err)
	}

	return g
}

func (rat *Rating) MarshalJSON() ([]byte, error) {
	return []byte(`"` + rat.String() + `"`), nil
}

type UnmarshalJSONRatingError struct {
	Data string `json:"data"`
	Err  error  `json:"error"`
}

func (e UnmarshalJSONRatingError) Error() string {
	return fmt.Sprintf("error parsing Rating `%s`: %v", e.Data, e.Err)
}

func (rat *Rating) UnmarshalJSON(data []byte) error {
	var tmp string

	if errU := json.Unmarshal(data, &tmp); errU != nil {
		return UnmarshalJSONRatingError{
			Data: string(data),
			Err:  errU,
		}
	}

	var err error

	*rat, err = ParseRatingFromString(tmp)
	if err != nil {
		return UnmarshalJSONRatingError{
			Data: string(data),
			Err:  err,
		}
	}

	return nil
}
